/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CALCULADORA_NETBEANS;

/**
 *
 * @author nicolas
 *///ATRIBUTOS///
public class cientifica extends javax.swing.JFrame {
  private String cadenas_numeros="";
    private String operaciones="nula";
    private double primernumero,resultado;
    private boolean Activado= true;
    private boolean punto= true;
    private double pi=3.14;
    public cientifica() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        etiqueta_numeros = new javax.swing.JTextArea();
        panel_cientifica = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bton_basica_calcu = new javax.swing.JButton();
        bton_modos_2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bton_MR_cientifica = new javax.swing.JButton();
        bton_MC_cientifica = new javax.swing.JButton();
        bton_MS_cientifica = new javax.swing.JButton();
        bton_menosM_cientifica = new javax.swing.JButton();
        bton_rad_cientifica = new javax.swing.JButton();
        bton_ANS_cientifica = new javax.swing.JButton();
        bton_ABS_cientifica = new javax.swing.JButton();
        bton_RND_cientifica = new javax.swing.JButton();
        bton_unoekis_cientifica = new javax.swing.JButton();
        bton_IN_cientifica = new javax.swing.JButton();
        bton_potencia_cientifica = new javax.swing.JButton();
        bton_raiz_cientifica = new javax.swing.JButton();
        bton_pi_cientifica = new javax.swing.JButton();
        bton_e_cientifica = new javax.swing.JButton();
        boton_diferentede_cientifica = new javax.swing.JButton();
        bton_log_cientifica = new javax.swing.JButton();
        bton_C = new javax.swing.JButton();
        bton_7_cientifica = new javax.swing.JButton();
        bton_4_cientifica = new javax.swing.JButton();
        bton_1_cientifica = new javax.swing.JButton();
        bton_coma_cientifica = new javax.swing.JButton();
        bton_SIN_cientifica = new javax.swing.JButton();
        bton_parentesis_cientifica = new javax.swing.JButton();
        bton_ocho_cientifica = new javax.swing.JButton();
        boton_cinco_cientifica = new javax.swing.JButton();
        boton_2_cientifica = new javax.swing.JButton();
        boton_cero_cientifica = new javax.swing.JButton();
        bton_COS_cientifica = new javax.swing.JButton();
        bton_porcentaje_cientifica = new javax.swing.JButton();
        bton_nueve_cientifica = new javax.swing.JButton();
        bton_seis_cientifica = new javax.swing.JButton();
        bton_3_cientifica = new javax.swing.JButton();
        bton_CE_cientifica = new javax.swing.JButton();
        bton_TAN_cientifica = new javax.swing.JButton();
        bton_dividir_cientifica = new javax.swing.JButton();
        bton_suma_cientifica = new javax.swing.JButton();
        boton_menos_cientifica = new javax.swing.JButton();
        btn_multi_cientifica = new javax.swing.JButton();
        boton_igual_cientifica = new javax.swing.JButton();
        etiqueta_numeros2 = new javax.swing.JLabel();
        etiqueta_numeros3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setViewportView(jEditorPane1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jMenu1.setText("jMenu1");

        etiqueta_numeros.setColumns(20);
        etiqueta_numeros.setRows(5);
        jScrollPane1.setViewportView(etiqueta_numeros);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("calculadora cientifica");

        bton_basica_calcu.setText("basica");
        bton_basica_calcu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bton_basica_calcuMouseClicked(evt);
            }
        });

        bton_modos_2.setText("modos");
        bton_modos_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bton_modos_2MouseClicked(evt);
            }
        });

        jButton3.setText("+-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bton_MR_cientifica.setText("MR");
        bton_MR_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_MR_cientificaActionPerformed(evt);
            }
        });

        bton_MC_cientifica.setText("MC");

        bton_MS_cientifica.setText("MS");
        bton_MS_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_MS_cientificaActionPerformed(evt);
            }
        });

        bton_menosM_cientifica.setText("M-");
        bton_menosM_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_menosM_cientificaActionPerformed(evt);
            }
        });

        bton_rad_cientifica.setText("RAD");
        bton_rad_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_rad_cientificaActionPerformed(evt);
            }
        });

        bton_ANS_cientifica.setText("ASIN");
        bton_ANS_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_ANS_cientificaActionPerformed(evt);
            }
        });

        bton_ABS_cientifica.setText("ABS");
        bton_ABS_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_ABS_cientificaActionPerformed(evt);
            }
        });

        bton_RND_cientifica.setText("RND");
        bton_RND_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_RND_cientificaActionPerformed(evt);
            }
        });

        bton_unoekis_cientifica.setText("1/X");
        bton_unoekis_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_unoekis_cientificaActionPerformed(evt);
            }
        });

        bton_IN_cientifica.setText("LN");
        bton_IN_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_IN_cientificaActionPerformed(evt);
            }
        });

        bton_potencia_cientifica.setText("^");
        bton_potencia_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_potencia_cientificaActionPerformed(evt);
            }
        });

        bton_raiz_cientifica.setText("raiz");
        bton_raiz_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_raiz_cientificaActionPerformed(evt);
            }
        });

        bton_pi_cientifica.setText("π");
        bton_pi_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_pi_cientificaActionPerformed(evt);
            }
        });

        bton_e_cientifica.setText("e");
        bton_e_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_e_cientificaActionPerformed(evt);
            }
        });

        boton_diferentede_cientifica.setText("!");

        bton_log_cientifica.setText("LOG");
        bton_log_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_log_cientificaActionPerformed(evt);
            }
        });

        bton_C.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        bton_C.setText("C");
        bton_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_CActionPerformed(evt);
            }
        });

        bton_7_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_7_cientifica.setText("7");
        bton_7_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_7_cientificaActionPerformed(evt);
            }
        });

        bton_4_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_4_cientifica.setText("4");
        bton_4_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_4_cientificaActionPerformed(evt);
            }
        });

        bton_1_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_1_cientifica.setText("1");
        bton_1_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_1_cientificaActionPerformed(evt);
            }
        });

        bton_coma_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_coma_cientifica.setText(",");
        bton_coma_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_coma_cientificaActionPerformed(evt);
            }
        });

        bton_SIN_cientifica.setText("SeN");
        bton_SIN_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_SIN_cientificaActionPerformed(evt);
            }
        });

        bton_parentesis_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_parentesis_cientifica.setText("()");
        bton_parentesis_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_parentesis_cientificaActionPerformed(evt);
            }
        });

        bton_ocho_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_ocho_cientifica.setText("8");
        bton_ocho_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_ocho_cientificaActionPerformed(evt);
            }
        });

        boton_cinco_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_cinco_cientifica.setText("5");
        boton_cinco_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cinco_cientificaActionPerformed(evt);
            }
        });

        boton_2_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_2_cientifica.setText("2");
        boton_2_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_2_cientificaActionPerformed(evt);
            }
        });

        boton_cero_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_cero_cientifica.setText("0");
        boton_cero_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cero_cientificaActionPerformed(evt);
            }
        });

        bton_COS_cientifica.setText("COS");
        bton_COS_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_COS_cientificaActionPerformed(evt);
            }
        });

        bton_porcentaje_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_porcentaje_cientifica.setText("%");
        bton_porcentaje_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_porcentaje_cientificaActionPerformed(evt);
            }
        });

        bton_nueve_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_nueve_cientifica.setText("9");
        bton_nueve_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_nueve_cientificaActionPerformed(evt);
            }
        });

        bton_seis_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_seis_cientifica.setText("6");
        bton_seis_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_seis_cientificaActionPerformed(evt);
            }
        });

        bton_3_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_3_cientifica.setText("3");
        bton_3_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_3_cientificaActionPerformed(evt);
            }
        });

        bton_CE_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_CE_cientifica.setText("CE");
        bton_CE_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_CE_cientificaActionPerformed(evt);
            }
        });

        bton_TAN_cientifica.setText("TAN");
        bton_TAN_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_TAN_cientificaActionPerformed(evt);
            }
        });

        bton_dividir_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_dividir_cientifica.setText("/");
        bton_dividir_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_dividir_cientificaActionPerformed(evt);
            }
        });

        bton_suma_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bton_suma_cientifica.setText("+");
        bton_suma_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_suma_cientificaActionPerformed(evt);
            }
        });

        boton_menos_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_menos_cientifica.setText("-");
        boton_menos_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_menos_cientificaActionPerformed(evt);
            }
        });

        btn_multi_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_multi_cientifica.setText("*");
        btn_multi_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multi_cientificaActionPerformed(evt);
            }
        });

        boton_igual_cientifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_igual_cientifica.setText("=");
        boton_igual_cientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_igual_cientificaActionPerformed(evt);
            }
        });

        etiqueta_numeros2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        etiqueta_numeros2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta_numeros2.setText("0");

        etiqueta_numeros3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta_numeros3.setText("0");

        javax.swing.GroupLayout panel_cientificaLayout = new javax.swing.GroupLayout(panel_cientifica);
        panel_cientifica.setLayout(panel_cientificaLayout);
        panel_cientificaLayout.setHorizontalGroup(
            panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cientificaLayout.createSequentialGroup()
                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cientificaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiqueta_numeros2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_cientificaLayout.createSequentialGroup()
                        .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(bton_IN_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bton_rad_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_cientificaLayout.createSequentialGroup()
                                .addComponent(bton_MR_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bton_MC_cientifica, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_cientificaLayout.createSequentialGroup()
                                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bton_ANS_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(bton_log_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bton_ABS_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bton_SIN_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(6, 6, 6)
                        .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bton_MS_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(bton_RND_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bton_COS_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bton_menosM_cientifica, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bton_TAN_cientifica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addComponent(bton_unoekis_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panel_cientificaLayout.createSequentialGroup()
                        .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_cientificaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bton_basica_calcu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bton_modos_2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_cientificaLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_cientificaLayout.createSequentialGroup()
                                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panel_cientificaLayout.createSequentialGroup()
                                        .addComponent(boton_diferentede_cientifica, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bton_coma_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_cientificaLayout.createSequentialGroup()
                                        .addComponent(bton_potencia_cientifica, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bton_C, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_cientificaLayout.createSequentialGroup()
                                        .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(bton_raiz_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(bton_e_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bton_pi_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_cientificaLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(bton_4_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(panel_cientificaLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(bton_1_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(panel_cientificaLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(bton_7_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(boton_2_cientifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boton_cinco_cientifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bton_ocho_cientifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bton_parentesis_cientifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(boton_cero_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bton_3_cientifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bton_seis_cientifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bton_nueve_cientifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bton_porcentaje_cientifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bton_CE_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boton_igual_cientifica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_multi_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boton_menos_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bton_dividir_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(bton_suma_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(etiqueta_numeros3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_cientificaLayout.setVerticalGroup(
            panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cientificaLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bton_basica_calcu)
                    .addComponent(bton_modos_2))
                .addGap(18, 18, 18)
                .addComponent(etiqueta_numeros3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta_numeros2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(bton_MR_cientifica)
                    .addComponent(bton_MC_cientifica)
                    .addComponent(bton_MS_cientifica)
                    .addComponent(bton_menosM_cientifica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bton_rad_cientifica)
                    .addComponent(bton_ANS_cientifica)
                    .addComponent(bton_ABS_cientifica)
                    .addComponent(bton_RND_cientifica)
                    .addComponent(bton_unoekis_cientifica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bton_IN_cientifica)
                    .addComponent(bton_log_cientifica)
                    .addComponent(bton_SIN_cientifica)
                    .addComponent(bton_COS_cientifica)
                    .addComponent(bton_TAN_cientifica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bton_C)
                        .addComponent(bton_parentesis_cientifica)
                        .addComponent(bton_porcentaje_cientifica)
                        .addComponent(bton_dividir_cientifica))
                    .addComponent(bton_potencia_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bton_7_cientifica)
                        .addComponent(bton_ocho_cientifica)
                        .addComponent(bton_nueve_cientifica)
                        .addComponent(bton_suma_cientifica))
                    .addComponent(bton_raiz_cientifica, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bton_4_cientifica)
                        .addComponent(boton_cinco_cientifica)
                        .addComponent(bton_seis_cientifica)
                        .addComponent(boton_menos_cientifica))
                    .addComponent(bton_pi_cientifica, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bton_1_cientifica)
                        .addComponent(boton_2_cientifica)
                        .addComponent(bton_3_cientifica)
                        .addComponent(btn_multi_cientifica))
                    .addComponent(bton_e_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_cientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bton_coma_cientifica)
                        .addComponent(boton_cero_cientifica)
                        .addComponent(bton_CE_cientifica)
                        .addComponent(boton_igual_cientifica))
                    .addComponent(boton_diferentede_cientifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_cientifica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_cientifica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//////boton para poner la calcu basica en la cientifica///
    private void bton_basica_calcuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bton_basica_calcuMouseClicked
        Calculadora calcu= new Calculadora();
        calcu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bton_basica_calcuMouseClicked
/////boton -m//// EN DESARROLLO 
    private void bton_menosM_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_menosM_cientificaActionPerformed
     if(Activado==true){
       etiqueta_numeros2.setText("m-"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado=Math.tan(primernumero);
       etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "m-";
       Activado= false;
         punto=true; }    
    }//GEN-LAST:event_bton_menosM_cientificaActionPerformed
/////bton +/-/////
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      if(cadenas_numeros.charAt(0)!='-'){
        cadenas_numeros="-"+ cadenas_numeros;
        }else{
        cadenas_numeros= cadenas_numeros.substring(1,cadenas_numeros.length());
        }
        etiqueta_numeros.setText(cadenas_numeros);
    }//GEN-LAST:event_jButton3ActionPerformed
/////boton mr////
    private void bton_MR_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_MR_cientificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bton_MR_cientificaActionPerformed
////////numero 3////
    private void bton_3_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_3_cientificaActionPerformed
         if(etiqueta_numeros2.getText().equals("0")){
     cadenas_numeros="3";
     }else{
     cadenas_numeros +="3";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;
    }//GEN-LAST:event_bton_3_cientificaActionPerformed
//////bton dividir////
    private void bton_dividir_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_dividir_cientificaActionPerformed
        if(Activado==true){
           primernumero= Double.parseDouble(cadenas_numeros);
           etiqueta_numeros2.setText(cadenas_numeros +"/");
       cadenas_numeros="";
       operaciones= "dividir";
       Activado= false;
          punto=true;
         }
    }//GEN-LAST:event_bton_dividir_cientificaActionPerformed
//////BOTON TAN DE TANGENTE///
    private void bton_TAN_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_TAN_cientificaActionPerformed
        if(Activado==true){
       etiqueta_numeros2.setText("tan"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado=Math.tan(primernumero);
       etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "tan";
       Activado= false;
         punto=true; } 
    }//GEN-LAST:event_bton_TAN_cientificaActionPerformed
////BOTON MODOS PARA PONER EL TIPO DE CALCULADORA DESEADA////
    private void bton_modos_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bton_modos_2MouseClicked
        vistas modos= new vistas();
        modos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bton_modos_2MouseClicked
///////////////numero7////////////
    private void bton_7_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_7_cientificaActionPerformed
       if(etiqueta_numeros2.getText().equals("0")){
     cadenas_numeros="7";
     }else{
     cadenas_numeros +="7";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;
    }//GEN-LAST:event_bton_7_cientificaActionPerformed
/////////////numero8///
    private void bton_ocho_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_ocho_cientificaActionPerformed
         if(etiqueta_numeros2.getText().equals("0")){
     cadenas_numeros="8";
     }else{
     cadenas_numeros +="8";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;
    }//GEN-LAST:event_bton_ocho_cientificaActionPerformed
//////////////////////numero9////
    private void bton_nueve_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_nueve_cientificaActionPerformed
           if(etiqueta_numeros2.getText().equals("0")){
     cadenas_numeros="9";
     }else{
     cadenas_numeros +="9";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;
    }//GEN-LAST:event_bton_nueve_cientificaActionPerformed
//////////////numero 4///////////////
    private void bton_4_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_4_cientificaActionPerformed
          if(etiqueta_numeros2.getText().equals("0")){
     cadenas_numeros="4";
     }else{
     cadenas_numeros +="4";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;
    }//GEN-LAST:event_bton_4_cientificaActionPerformed
////////////////numero5///////////
    private void boton_cinco_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cinco_cientificaActionPerformed
        if(etiqueta_numeros2.getText().equals("0")){
     cadenas_numeros="5";
     }else{
     cadenas_numeros +="5";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;
    }//GEN-LAST:event_boton_cinco_cientificaActionPerformed
/////numero 6////
    private void bton_seis_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_seis_cientificaActionPerformed
         if(etiqueta_numeros2.getText().equals("0")){
     cadenas_numeros="6";
     }else{
     cadenas_numeros +="6";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;
    }//GEN-LAST:event_bton_seis_cientificaActionPerformed
///////numero1///
    private void bton_1_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_1_cientificaActionPerformed
         if(etiqueta_numeros2.getText().equals("0")){
     cadenas_numeros="1";
     }else{
     cadenas_numeros +="1";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;

    }//GEN-LAST:event_bton_1_cientificaActionPerformed
                //numero2////
    private void boton_2_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_2_cientificaActionPerformed
 if(etiqueta_numeros2.getText().equals("0")){
     cadenas_numeros="2";
     }else{
     cadenas_numeros +="2";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;
    }//GEN-LAST:event_boton_2_cientificaActionPerformed
//////numero0/////
    private void boton_cero_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cero_cientificaActionPerformed
     if(etiqueta_numeros2.getText().equals("0")){
     cadenas_numeros="0";
     }else{
     cadenas_numeros +="0";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;
    }//GEN-LAST:event_boton_cero_cientificaActionPerformed
//////bton coma////
    private void bton_coma_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_coma_cientificaActionPerformed
         if(punto==true){
        if(cadenas_numeros.equals("")){
        cadenas_numeros="0.";
        }else{
        cadenas_numeros+=".";
        }
        }
        etiqueta_numeros2.setText(cadenas_numeros);
        punto=false;
    }//GEN-LAST:event_bton_coma_cientificaActionPerformed
//////bton suma////
    private void bton_suma_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_suma_cientificaActionPerformed
       if(Activado==true){
           primernumero= Double.parseDouble(cadenas_numeros);
           etiqueta_numeros2.setText(cadenas_numeros +"+");
       cadenas_numeros="";
       operaciones= "sumar";
       Activado= false;
       punto=true;
       }
        
    }//GEN-LAST:event_bton_suma_cientificaActionPerformed
/////////////bton multi//////
    private void btn_multi_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multi_cientificaActionPerformed
    if(Activado==true){
           primernumero= Double.parseDouble(cadenas_numeros);
           etiqueta_numeros2.setText(cadenas_numeros +"x");
       cadenas_numeros="";
       operaciones= "multiplicar";
       Activado= false;
        punto=true;
       }
    }//GEN-LAST:event_btn_multi_cientificaActionPerformed
///bton_menos///
    
    
    private void boton_menos_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_menos_cientificaActionPerformed
        if(Activado==true){
           primernumero= Double.parseDouble(cadenas_numeros);
           etiqueta_numeros2.setText(cadenas_numeros +"-");
       cadenas_numeros="";
       operaciones= "restar";
       Activado= false;
         punto=true;
        
     }
    }//GEN-LAST:event_boton_menos_cientificaActionPerformed
//////boton c/////
    private void bton_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_CActionPerformed
      etiqueta_numeros2.setText("");
        etiqueta_numeros2.setText("0");
        operaciones="nula";
       Activado=true;
       punto=true;
    }//GEN-LAST:event_bton_CActionPerformed
/////BOTON CE////
    private void bton_CE_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_CE_cientificaActionPerformed
        int tamaño= cadenas_numeros.length();
        if(tamaño>0){
        if(tamaño==1){
        cadenas_numeros="0";
        }else{
        cadenas_numeros=cadenas_numeros.substring(0,cadenas_numeros.length()-1);
        }
        }
        etiqueta_numeros2.setText(cadenas_numeros);
    }//GEN-LAST:event_bton_CE_cientificaActionPerformed
/////BOTON RAIZ////
    private void bton_raiz_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_raiz_cientificaActionPerformed
       primernumero= Double.parseDouble(cadenas_numeros);
        etiqueta_numeros2.setText("sqrt("+cadenas_numeros+")");
        resultado= Math.sqrt(primernumero);
        etiqueta_numeros2.setText(String.format("%.2f",resultado));
        cadenas_numeros= String.valueOf(resultado);
         punto=true;
    }//GEN-LAST:event_bton_raiz_cientificaActionPerformed
/////7BOTON PARENTESIS///
    private void bton_parentesis_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_parentesis_cientificaActionPerformed
       if(etiqueta_numeros2.getText().equals("()")){
     cadenas_numeros="()";
     }else{
     cadenas_numeros +="()";
     }
     etiqueta_numeros2.setText(cadenas_numeros);
     Activado= true;
    }//GEN-LAST:event_bton_parentesis_cientificaActionPerformed
//////BOTON PORCENTAJE///
    private void bton_porcentaje_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_porcentaje_cientificaActionPerformed
      if(Activado==true){
      Double Segundo_numero;    
       Segundo_numero= Double.parseDouble(cadenas_numeros);
          etiqueta_numeros2.setText("%("+cadenas_numeros+")");
          resultado= primernumero * Segundo_numero/100;
          etiqueta_numeros2.setText(String.format("%.2f",resultado));
       cadenas_numeros=String.valueOf(resultado);;
       punto=true;
       
       
        }
    }//GEN-LAST:event_bton_porcentaje_cientificaActionPerformed
///////BOTON IGUAL////
    private void boton_igual_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_igual_cientificaActionPerformed
       Double Segundo_numero;
       if(operaciones.equals("sumar")){
       Segundo_numero= Double.parseDouble(cadenas_numeros);
       resultado= primernumero + Segundo_numero;
       etiqueta_numeros2.setText(String.format("%.2f", resultado));
       cadenas_numeros= String.valueOf(resultado);/////el value of convierte una variable x en String
       operaciones="nula";
       }////fin de summa
       etiqueta_numeros3.setText("");
       Activado=true;
       ///resta
       if(operaciones.equals("restar")){
       Segundo_numero= Double.parseDouble(cadenas_numeros);
       resultado= primernumero - Segundo_numero;
       etiqueta_numeros2.setText(String.format("%.2f", resultado));
       cadenas_numeros= String.valueOf(resultado);/////el value of convierte una variable x en String
       operaciones="nula";
       }
       etiqueta_numeros3.setText("");
       Activado=true;
       /////MULTIPLICAR///
       if(operaciones.equals("multiplicar")){
       Segundo_numero= Double.parseDouble(cadenas_numeros);
       resultado= primernumero * Segundo_numero;
       etiqueta_numeros2.setText(String.format("%.2f", resultado));
       cadenas_numeros= String.valueOf(resultado);/////el value of convierte una variable x en String
       operaciones="nula";
       }
       etiqueta_numeros3.setText("");
       Activado=true;
       ///dividir//
       if(operaciones.equals("dividir")){
       Segundo_numero= Double.parseDouble(cadenas_numeros);
       if(Segundo_numero==0){
       etiqueta_numeros2.setText("SYNTAX ERROR ");
       }else{
      resultado= primernumero / Segundo_numero;
       etiqueta_numeros2.setText(String.format("%.2f", resultado));
       cadenas_numeros= String.valueOf(resultado);/////el value of convierte una variable x en String
       operaciones="nula";
       }
       etiqueta_numeros3.setText("");
       Activado=true;
       }if(operaciones.equals("potencia")){
        Segundo_numero= Double.parseDouble(cadenas_numeros);
        resultado=Math.pow(primernumero, Segundo_numero);
       etiqueta_numeros2.setText(String.format("%.2f", resultado));
       operaciones="nula";
       }
        etiqueta_numeros3.setText("");
       Activado=true;
      ////7NUMERO PI///
      
    }//GEN-LAST:event_boton_igual_cientificaActionPerformed
/////boton potencia///
    private void bton_potencia_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_potencia_cientificaActionPerformed
     if(Activado==true){
           primernumero= Double.parseDouble(cadenas_numeros);
           etiqueta_numeros2.setText(cadenas_numeros +"^");
       cadenas_numeros="";
       operaciones= "potencia";
       Activado= false;
       punto=true;
  
       }
    }//GEN-LAST:event_bton_potencia_cientificaActionPerformed
/////boton PI///
    private void bton_pi_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_pi_cientificaActionPerformed
         if(Activado==true){
           Double pi=3.14;
           primernumero=Double.parseDouble(cadenas_numeros);
           etiqueta_numeros2.setText("π("+cadenas_numeros+")");
           resultado=Math.PI*primernumero;
         etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           punto=true;
        }
    }//GEN-LAST:event_bton_pi_cientificaActionPerformed
////boton E/////
    private void bton_e_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_e_cientificaActionPerformed
        if(Activado==true){
           Double pi=2.71828;
           primernumero=Double.parseDouble(cadenas_numeros);
           etiqueta_numeros2.setText("π("+cadenas_numeros+")");
           resultado=pi*primernumero;
         etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           punto=true;}
    }//GEN-LAST:event_bton_e_cientificaActionPerformed
/////boton LN(logaritmos naturales)/////
    private void bton_IN_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_IN_cientificaActionPerformed
     if(Activado==true){
       etiqueta_numeros2.setText("Ln"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado=Math.log(primernumero);
         etiqueta_numeros2.setText(String.format("%.3f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "lognatural";
       Activado= false;
         punto=true; }
    }//GEN-LAST:event_bton_IN_cientificaActionPerformed
//////boton LOG10(logaritmos en base 10)
    private void bton_log_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_log_cientificaActionPerformed
         if(Activado==true){
       etiqueta_numeros2.setText("Log"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado=Math.log10(primernumero);
         etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "lognaturalbase10";
       Activado= false;
         punto=true; }
    }//GEN-LAST:event_bton_log_cientificaActionPerformed
//////boton ABS(valor absoluto)
    private void bton_ABS_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_ABS_cientificaActionPerformed
         if(Activado==true){
       etiqueta_numeros2.setText("ABS"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado=Math.abs(primernumero);
       etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "abs";
       Activado= false;
         punto=true; }        
           
        
    }//GEN-LAST:event_bton_ABS_cientificaActionPerformed
//////boton radianes////
    private void bton_rad_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_rad_cientificaActionPerformed
        if(Activado==true){
       etiqueta_numeros2.setText("RAD"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado=Math.toRadians(primernumero);
       etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "RAD";
       Activado= false;
         punto=true; }  
    }//GEN-LAST:event_bton_rad_cientificaActionPerformed
//////boton seno////
    private void bton_SIN_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_SIN_cientificaActionPerformed
        if(Activado==true){
       etiqueta_numeros2.setText("sin"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado=Math.sin(primernumero);
       etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "sin";
       Activado= false;
         punto=true; }  
    }//GEN-LAST:event_bton_SIN_cientificaActionPerformed
////boton coseno///
    private void bton_COS_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_COS_cientificaActionPerformed
      if(Activado==true){
       etiqueta_numeros2.setText("cos"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado=Math.cos(primernumero);
       etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "cos";
       Activado= false;
         punto=true; }
    }//GEN-LAST:event_bton_COS_cientificaActionPerformed
////boton asin///
    private void bton_ANS_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_ANS_cientificaActionPerformed
        if(Activado==true){
       etiqueta_numeros2.setText("asin"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado=Math.asin(primernumero);
       etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "asin";
       Activado= false;
         punto=true; }
    }//GEN-LAST:event_bton_ANS_cientificaActionPerformed
//////boton rnd/////
    private void bton_RND_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_RND_cientificaActionPerformed
        if(Activado==true){
       etiqueta_numeros2.setText("rnd"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado=Math.round(primernumero);
       etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "rnd";
       Activado= false;
         punto=true; }
    }//GEN-LAST:event_bton_RND_cientificaActionPerformed
////boton 1/x////
    private void bton_unoekis_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_unoekis_cientificaActionPerformed
      if(Activado==true){
       etiqueta_numeros2.setText("1/x"+cadenas_numeros );
       primernumero= Double.parseDouble(cadenas_numeros);
      resultado= 1/primernumero;
       etiqueta_numeros2.setText(String.format("%.2f",resultado));
         cadenas_numeros=String.valueOf(resultado);;
           operaciones= "1/x";
       Activado= false;
         punto=true; }
    }//GEN-LAST:event_bton_unoekis_cientificaActionPerformed
/////BOTON MS EN DESARROLLO///
    private void bton_MS_cientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_MS_cientificaActionPerformed
        
    }//GEN-LAST:event_bton_MS_cientificaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cientifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_2_cientifica;
    private javax.swing.JButton boton_cero_cientifica;
    private javax.swing.JButton boton_cinco_cientifica;
    private javax.swing.JButton boton_diferentede_cientifica;
    private javax.swing.JButton boton_igual_cientifica;
    private javax.swing.JButton boton_menos_cientifica;
    private javax.swing.JButton btn_multi_cientifica;
    private javax.swing.JButton bton_1_cientifica;
    private javax.swing.JButton bton_3_cientifica;
    private javax.swing.JButton bton_4_cientifica;
    private javax.swing.JButton bton_7_cientifica;
    private javax.swing.JButton bton_ABS_cientifica;
    private javax.swing.JButton bton_ANS_cientifica;
    private javax.swing.JButton bton_C;
    private javax.swing.JButton bton_CE_cientifica;
    private javax.swing.JButton bton_COS_cientifica;
    private javax.swing.JButton bton_IN_cientifica;
    private javax.swing.JButton bton_MC_cientifica;
    private javax.swing.JButton bton_MR_cientifica;
    private javax.swing.JButton bton_MS_cientifica;
    private javax.swing.JButton bton_RND_cientifica;
    private javax.swing.JButton bton_SIN_cientifica;
    private javax.swing.JButton bton_TAN_cientifica;
    private javax.swing.JButton bton_basica_calcu;
    private javax.swing.JButton bton_coma_cientifica;
    private javax.swing.JButton bton_dividir_cientifica;
    private javax.swing.JButton bton_e_cientifica;
    private javax.swing.JButton bton_log_cientifica;
    private javax.swing.JButton bton_menosM_cientifica;
    private javax.swing.JButton bton_modos_2;
    private javax.swing.JButton bton_nueve_cientifica;
    private javax.swing.JButton bton_ocho_cientifica;
    private javax.swing.JButton bton_parentesis_cientifica;
    private javax.swing.JButton bton_pi_cientifica;
    private javax.swing.JButton bton_porcentaje_cientifica;
    private javax.swing.JButton bton_potencia_cientifica;
    private javax.swing.JButton bton_rad_cientifica;
    private javax.swing.JButton bton_raiz_cientifica;
    private javax.swing.JButton bton_seis_cientifica;
    private javax.swing.JButton bton_suma_cientifica;
    private javax.swing.JButton bton_unoekis_cientifica;
    private javax.swing.JTextArea etiqueta_numeros;
    private javax.swing.JLabel etiqueta_numeros2;
    private javax.swing.JLabel etiqueta_numeros3;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel_cientifica;
    // End of variables declaration//GEN-END:variables
}
